version: '3.4'

services:
    messagemicroservice_seq:
        image: datalust/seq:latest
        environment:
            ACCEPT_EULA: Y

    messagemicroservice_messagedb:
        image: redis #Redis offical image name is redis

    messagemicroservice_message.api:
        image: ${DOCKER_REGISTRY-}messagemicroservice_messageapi
        build:
            context: .
            dockerfile: src/Message/Message.API/Dockerfile

    messagemicroservice_userdb:
        image: redis #Redis offical image name is redis

    messagemicroservice_user.api:
        image: ${DOCKER_REGISTRY-}messagemicroservice_userapi
        build:
            context: .
            dockerfile: src/User/User.API/Dockerfile

